### ISSUE TITLE
Message Base not correctly reflecting new messages

### ISSUE THREAD

**Issue by granitepenguin** [apamment/MagickaBBS#1]
I originally thought this was a display issue.  I had selected Agoranet General Chat (that has 10 messages) and selected "N" to display new messages. 

> Scan for new mail? (Y/N) :      y
> 0. Local Mail
>    --> 0. General Discussion (2 new)
>    --> 3. Testing (5 new)
> 
> 1. Agoranet
>    --> 0. Test (89 new)  
>    --> 1. League Scores & Recons (282 new)  
>    --> 2. Hub Stats (72 new)  
>    --> 3. BBS and Network Ads (131 new)  
>    --> 4. BBS Discussion (139 new)  
>    --> 5. General Chat (10 new)  
>                       
> Conf: (1) Agoranet
> Area: (5) General Chat
> TL: 224m :> l
> Start at message [1-10] or N for New? n        
> 
> [MSG#] Subject                   From            To              Date
> [   2]\*Jobs?!                    Accession       PureSkillz      03:54 04-04-16
> [   3]\*Jobs?!                    Robert Wolfe    Pureskillz      11:09 11-04-16
> [   4]\*Jobs?!                    PureSkillz      Robert Wolfe    19:53 11-04-16
> [   5]\*Jobs?!                    Robert Wolfe    Pureskillz      20:20 11-04-16
> [   6]\*STUTTERSHIT               Caphood         All             23:46 20-04-16
> [   7]\*flupH is back online      Skuz            All             22:55 28-04-16
> [   8]\*Im back...                m00p            All             05:01 03-05-16
> [   9]\*Im back...                Caphood         m00p            00:06 03-05-16
> [  10]\*Im back...                Tiny            m00p            03:22 03-05-16
> (#) Read Message # (ENTER) Quit
                                  
notice how message #1 doesn't display.  Turns out that's because message #1 is not flagged as new.  I thought maybe I had read it, so tried some other message bases that I know I have not read.  They all do the same thing.  Apparently, every message base is flagging message #1 as read, so if I list all new messages, message #1 is not displayed.

**Comment by apamment** [comment]
Thanks, I'll have a look at it.

**Comment by apamment** [comment]
Fixed now I think, thanks :)

**Comment by granitepenguin** [comment]
Yup, looks a lot better from my end.
